# Generated by Django 5.0.3 on 2024-04-08 10:55

import timetracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='employee',
            field=models.CharField(max_length=100, verbose_name=timetracker.models.Employee),
        ),
    ]
