# Generated by Django 5.0.3 on 2024-04-08 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0002_alter_timeentry_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetracker.employee'),
        ),
    ]
